Payload parameters
mirakl/terraform-google-gcr-cleaner pull request #15
Opened 2021-06-23 09:41 UTC by foxted

I'm new to Terraform, but I gave it a shot to try and help. If you had a different implementation in mind, please let me know, happy to help 👍🏻 

Example with `repositories`: 

```terraform
module "gcr_cleaner" {
  source = "mirakl/gcr-cleaner/google"
  version = "0.5.0"

  app_engine_application_location = "northamerica-northeast1"

  gcr_repositories = [
    {
      repositories = [
        {
          repo = "gcr.io/example/repository"
          allow_tagged = true
          keep = 10
          grace = "730s"       
        }
      ]
    },
  ]
}
```

Example with `clean_all`:

```terraform
module "gcr_cleaner" {
  source = "mirakl/gcr-cleaner/google"
  version = "0.5.0"

  app_engine_application_location = "northamerica-northeast1"

  gcr_repositories = [
    {
      clean_all = true
      parameters = {
        allow_tagged = true
        keep = 10
        grace = "730s"
      }
    },
  ]
}
```

2021-06-23 10:57 UTC, anouarchattouna commented
Hello @foxted, thank you for opening this PR.
Could you please update [examples](https://github.com/mirakl/terraform-google-gcr-cleaner/tree/main/examples) accordingly?

2021-06-23 20:50 UTC, foxted commented
No worries, updated the examples, sprinkling example on how to use the payload parameters.

2021-06-24 11:12 UTC, anouarchattouna requested changes
Please apply those changes on your project and run the jobs for validation

2021-06-24 11:12 UTC, anouarchattouna commented on locals.tf
> +        ? merge({
```suggestion
      ? merge(
        repo,
        {
          repo         = "${gcr.storage_region}.gcr.io/${gcr.project_id != null ? gcr.project_id : local.google_project_id}/${repo.repo}"
          grace        = repo.grace != null ? repo.grace : "0"
          allow_tagged = repo.allow_tagged != null ? repo.allow_tagged : false
          keep         = repo.keep != null ? repo.keep : 0
          tag_filter   = repo.tag_filter != null ? repo.tag_filter : ""
        }
      )
      : merge(
        repo,
        {
          repo         = "gcr.io/${gcr.project_id != null ? gcr.project_id : local.google_project_id}/${repo.repo}"
          grace        = repo.grace != null ? repo.grace : "0"
          allow_tagged = repo.allow_tagged != null ? repo.allow_tagged : false
          keep         = repo.keep != null ? repo.keep : 0
          tag_filter   = repo.tag_filter != null ? repo.tag_filter : ""
        }
      )
```
* need to switch maps order in order to keep elements from the 2end map
* need to handle null values

2021-06-24 11:12 UTC, anouarchattouna commented on locals.tf
> +      for repo in jsondecode(data.result.repositories) : merge({ "repo": repo.name }, local.options[repo.project_id])
```suggestion
      for repo in jsondecode(data.result.repositories) : merge(
        local.options[repo.project_id],
        {
          repo         = repo.name
          grace        = local.options[repo.project_id].grace != null ? local.options[repo.project_id].grace : "0"
          allow_tagged = local.options[repo.project_id].allow_tagged != null ? local.options[repo.project_id].allow_tagged : false
          keep         = local.options[repo.project_id].keep != null ? local.options[repo.project_id].keep : 0
          tag_filter   = local.options[repo.project_id].tag_filter != null ? local.options[repo.project_id].tag_filter : ""
        }
      )
```
* need to switch maps order in order to keep elements from the 2end map
* need to handle null values

2021-06-24 11:12 UTC, anouarchattouna commented on main.tf
> +    for idx, repo in concat(local.fetched_repositories, local.repositories): idx => repo
```suggestion
    for idx, repo in concat(local.fetched_repositories, local.repositories) : idx => repo
```

2021-06-24 18:07 UTC, foxted commented
@anouarchattouna I saw your comments, I'll update this tonight 👍🏻

2021-06-25 05:28 UTC, foxted commented
Changes applied :)

2021-06-25 09:48 UTC, anouarchattouna requested changes

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +              repo = "${gcr.storage_region}.gcr.io/${gcr.project_id != null ? gcr.project_id : local.google_project_id}/${repo.repo}",
```suggestion
              repo = "${gcr.storage_region}.gcr.io/${gcr.project_id != null ? gcr.project_id : local.google_project_id}/${repo.repo}"
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +              grace = repo.grace != null ? repo.grace : "0",
```suggestion
              grace = repo.grace != null ? repo.grace : "0"
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +              allow_tagged = repo.allow_tagged != null ? repo.allow_tagged : false,
```suggestion
              allow_tagged = repo.allow_tagged != null ? repo.allow_tagged : false
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +              repo = "gcr.io/${gcr.project_id != null ? gcr.project_id : local.google_project_id}/${repo.repo}",
```suggestion
              repo = "gcr.io/${gcr.project_id != null ? gcr.project_id : local.google_project_id}/${repo.repo}"
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +              grace = repo.grace != null ? repo.grace : "0",
```suggestion
              grace = repo.grace != null ? repo.grace : "0"
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +              allow_tagged = repo.allow_tagged != null ? repo.allow_tagged : false,
```suggestion
              allow_tagged = repo.allow_tagged != null ? repo.allow_tagged : false
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +          grace = local.options[repo.project_id].grace != null ? local.options[repo.project_id].grace : "0",
```suggestion
          grace = local.options[repo.project_id].grace != null ? local.options[repo.project_id].grace : "0"
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +          allow_tagged = local.options[repo.project_id].allow_tagged != null ? local.options[repo.project_id].allow_tagged : false,
```suggestion
          allow_tagged = local.options[repo.project_id].allow_tagged != null ? local.options[repo.project_id].allow_tagged : false
```

2021-06-25 09:48 UTC, anouarchattouna commented on locals.tf
> +          keep = local.options[repo.project_id].keep != null ? local.options[repo.project_id].keep : 0,
```suggestion
          keep = local.options[repo.project_id].keep != null ? local.options[repo.project_id].keep : 0
```

2021-07-13 19:16 UTC, CrackerJackMack commented
Pulled the latest in main, using multiple lines in the same project creates a key conflict.  The use case (requirement) for this is that using allow_tagged and tag_filter, you need to run them separated in order for the total count of images to be unique per tag.  Using a collapsed regex `^(main|master|dev)` results in only 10 images out a list containing all of those tags.  This produces less than ideal results.

```
module "gcr_cleaner" {
  source = "./gcr"

  gcr_repositories = [
    {
      // delete all untagged images
      project_id = "fart"
      clean_all  = true
    },
    {
      // in all repositories, keep 10 `main` builds, ignore anything newer than 5 days
      project_id = "fart"
      clean_all  = true
      parameters = {
        allow_tagged = true
        keep         = 10
        grace        = "5d"
        tag_filter   = "^main.+$"
      }
    },
    {
      // in all repositories, keep 10 `dev` builds, ignore anything newer than 5 days
      project_id = "fart"
      clean_all  = true
      parameters = {
        allow_tagged = true
        keep         = 10
        grace        = "5d"
        tag_filter   = "^dev.+$"
      }
    },
    {
      // keep only 2 master builds if they existed, just in case.
      project_id = "fart"
      clean_all  = true
      parameters = {
        allow_tagged = true
        keep         = 2
        tag_filter   = "^master.+$"
      }
    }
  ]
}
```

generates 
```
│ Error: Duplicate object key
│
│   on gcr/locals.tf line 63, in locals:
│   62:   options = {
│   63:     for gcr in var.gcr_repositories : (gcr.project_id != null ? gcr.project_id : local.google_project_id) => gcr.parameters
│   64:   }
│     ├────────────────
│     │ gcr.project_id is "fart"
│     │ local.google_project_id is "fart"
│
│ Two different items produced the key "fart" in this 'for' expression. If duplicates are expected, use the ellipsis (...) after the value expression to enable grouping by key.
```

2021-07-22 08:44 UTC, anouarchattouna commented
@CrackerJackMack thank you for that.
@foxted any thoughts? Could you please have a look on it?

2021-07-23 01:24 UTC, foxted commented
We might need to randomize or serialize the project names in the for loop. I didn't consider the use case where multiple configurations would be used for the same project. I'll have to go back to the drawing board.

2021-11-22 13:02 UTC, anouarchattouna commented
@CrackerJackMack, see #24

2022-01-10 17:43 UTC, anouarchattouna commented
Feature implemented in https://github.com/mirakl/terraform-google-gcr-cleaner/pull/24

2022-01-10 17:43 UTC, closed without merging