Enhancement: add project id parameter
mirakl/terraform-google-gcr-cleaner pull request #44
Opened 2022-02-07 11:19 UTC by patricklubach

# Pull Request Template

## Description

I needed to add a the project_id variable as I recognized that it is only possible to pass in the project id when the Google provider is configured through a variable. But I ran into a scenario where the project id comes from a terraform module that is not passable to the Google provider because this cause a circle of dependencies. So I introduced the project id variable to make it possible. The support for retrieving the project id through the Google provider is still there, but now the project_id variable takes precedence over the current implementation. The current implementation acts now as a fallback if the project id is not passed in as a variable.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This was tested with the minimal example in `examples/minimal` directory.

- [ ] Passed in no project id (nor through provider, neither by variable). Expectation: failure | Result: failure
- [ ] Passed in project id by provider only. Expectation: success | Result: success
- [ ] Passed in project id by variable only. Expectation: success | Result: success
- [ ] Passed in project id by provider and by variable. Expectation: success (variable value was taken) | Result: success

## Checklist:

- [ ] My PR title follows [semantics prefix](.github/CONTRIBUTING.md#semantic-pull-requests)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked my code and corrected any misspellings
- [ ] I have run pre-commit hooks `pre-commit run -a`
- [ ] CI tests are passing

2022-02-07 11:25 UTC, patricklubach commented
@anouarchattouna @PascalBourdier would you be so kind and review? :)

2022-02-15 10:38 UTC, patricklubach commented
Please someone of @anouarchattouna @PascalBourdier @mirakl-admin can you review?

2022-03-19 11:56 UTC, patricklubach commented
Does anyone has time for review? If not, I will continue developing it on my own.

2022-03-21 10:07 UTC, anouarchattouna requested changes

2022-03-21 10:07 UTC, anouarchattouna commented on locals.tf
>    # get project id (used by google provider)
```suggestion
  # get project id: either from project_id variable or from google provider.
```

2022-03-21 10:07 UTC, anouarchattouna commented on variables.tf
> +  description = "GCP project that the Cloud Run instances are being created."
```suggestion
  description = "The ID of the project to which the resource belongs. If it is not provided, the provider project is used."
```

2022-03-21 10:35 UTC, madhifallah approved these changes
LGTM

2022-03-27 07:23 UTC, patricklubach commented
@anouarchattouna I implement you requested changes. I don't get what is wrong now with the CI. Can you explain to me please?

2022-03-28 07:57 UTC, anouarchattouna approved these changes

2022-03-28 08:00 UTC, anouarchattouna commented
> @anouarchattouna I implement you requested changes. I don't get what is wrong now with the CI. Can you explain to me please?

Please run pre-commit again

2022-04-07 16:13 UTC, patricklubach commented
When running pre-commit I get the following output:

`
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform validate.......................................................Failed
- hook id: terraform_validate
- exit code: 1

Validation failed: examples/complete
╷
│ Warning: Experimental feature "module_variable_optional_attrs" is active
│ 
│   on ../../versions.tf line 3, in terraform:
│    3:   experiments      = [module_variable_optional_attrs]
│ 
│ Experimental features are subject to breaking changes in future minor or
│ patch releases, based on feedback.
│ 
│ If you have feedback on the design of this feature, please open a GitHub
│ issue to discuss it.
╵
╷
│ Error: Could not load plugin
│ 
│ 
│ Plugin reinitialization required. Please run "terraform init".
│ 
│ Plugins are external binaries that Terraform uses to access and manipulate
│ resources. The configuration provided requires plugins which can't be
│ located,
│ don't satisfy the version constraints, or are otherwise incompatible.
│ 
│ Terraform automatically discovers provider requirements from your
│ configuration, including providers used in child modules. To see the
│ requirements and constraints, run "terraform providers".
│ 
│ 2 problems:
│ 
│ - failed to instantiate provider "registry.terraform.io/hashicorp/google"
│ to obtain schema: there is no package for
│ registry.terraform.io/hashicorp/google 4.9.0 cached in .terraform/providers
│ - failed to instantiate provider
│ "registry.terraform.io/hashicorp/google-beta" to obtain schema: there is no
│ package for registry.terraform.io/hashicorp/google-beta 4.9.0 cached in
│ .terraform/providers
│ 
╵

Terraform docs...........................................................Failed
- hook id: terraform_docs
- files were modified by this hook
Terraform validate with tfsec............................................Passed
Terraform validate with tflint...........................................Passed
check for merge conflicts................................................Passed
`

When I run `terraform init` and `terraform validate` everything is fine and it succeeds. Does anyone know what's the cause?

2022-04-14 11:10 UTC, patricklubach commented
> When running pre-commit I get the following output:
> 
> ```
> $ pre-commit run -a
> Terraform fmt............................................................Passed
> Terraform validate.......................................................Failed
> - hook id: terraform_validate
> - exit code: 1
> 
> Validation failed: examples/complete
> ╷
> │ Warning: Experimental feature "module_variable_optional_attrs" is active
> │ 
> │   on ../../versions.tf line 3, in terraform:
> │    3:   experiments      = [module_variable_optional_attrs]
> │ 
> │ Experimental features are subject to breaking changes in future minor or
> │ patch releases, based on feedback.
> │ 
> │ If you have feedback on the design of this feature, please open a GitHub
> │ issue to discuss it.
> ╵
> ╷
> │ Error: Could not load plugin
> │ 
> │ 
> │ Plugin reinitialization required. Please run "terraform init".
> │ 
> │ Plugins are external binaries that Terraform uses to access and manipulate
> │ resources. The configuration provided requires plugins which can't be
> │ located,
> │ don't satisfy the version constraints, or are otherwise incompatible.
> │ 
> │ Terraform automatically discovers provider requirements from your
> │ configuration, including providers used in child modules. To see the
> │ requirements and constraints, run "terraform providers".
> │ 
> │ 2 problems:
> │ 
> │ - failed to instantiate provider "registry.terraform.io/hashicorp/google"
> │ to obtain schema: there is no package for
> │ registry.terraform.io/hashicorp/google 4.9.0 cached in .terraform/providers
> │ - failed to instantiate provider
> │ "registry.terraform.io/hashicorp/google-beta" to obtain schema: there is no
> │ package for registry.terraform.io/hashicorp/google-beta 4.9.0 cached in
> │ .terraform/providers
> │ 
> ╵
> 
> Terraform docs...........................................................Failed
> - hook id: terraform_docs
> - files were modified by this hook
> Terraform validate with tfsec............................................Passed
> Terraform validate with tflint...........................................Passed
> check for merge conflicts................................................Passed
> ```
> 
> When I run `terraform init` and `terraform validate` everything is fine and it succeeds. Does anyone know what's the cause?

okay there was an issue with the .terraform folder in `examples/complete`. Removed it, ran pre-commit again and it passed.

2022-05-25 03:26 UTC, closed without merging